"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-io' references
in its source tree. Outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Peer ROOT package not installed (standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip(root)`. Only the ROOT is
  skipped: the FULL submodule path is hard-imported afterwards, so an
  internal rename fails the gate even where it is the only deviation.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_dev",
    "scitex_dev._cli._completion",
    "scitex_dev.cli",
    "scitex_dev.linter._rules._base",
    "scitex_dev.linter.checker",
    "scitex_logging",
    "scitex_stats._utils._normalizers",
    "scitex_stats._dataclasses",
    "scitex_stats.io",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves_to_module(module_name):
    """Importing scitex-io's declared cross-package dependency must succeed."""
    # Arrange
    root = module_name.split(".")[0]
    # Act
    pytest.importorskip(root)
    mod = importlib.import_module(module_name)
    # Assert
    assert getattr(mod, "__name__", None) == module_name
